### PR TITLE
Added arguments for output path and png output

### PR DESCRIPTION
**Pull request by KlustoR**
As this functionality was important for me, i added it quickly.
Hope this can get merged.

Thanks

### CODE REVIEW

**Comment by mike42** [comment]
@KlustoR  - Change looks good, the failing check is for [PSR-2 code style](http://www.php-fig.org/psr/psr-2/) .

Can you please run it through the formatter and push an update?

Something like this should do it-

```bash
php vendor/bin/phpcbf --standard=psr2 --ignore=vendor -n .
git commit -a
git push
```

**Comment by KlustoR** [comment]
@mike42 It's giving me errors in almost every file ?
[Terminal output](https://pastebin.com/xuKZWjJh)

**Comment by mike42** [comment]
Not sure what `phpcs` is doing there on Mac.

I've fixed the formatting, and merged your work with  some modifications to improve error handling, documentation, and to allow for more output formats to be added in future without breaking any existing usage.

Documentation snippet below showing the new usage-

```
Usage: escimages.php OPTIONS --file 'filename'

 Required options:

  -f, --file FILE             The input file to read.

 Output options:

  -o, --output-dir DIRECTORY  The directory to write output files to.

 Output format:

  Select one or more formats for output. If none is specified, then PNG is used.

  --png                        Write output files in PNG format.
  --pbm                        Write output files in PBM format.

 Other options:
  -h, --help                   Show this help
```

**Comment by KlustoR** [comment]
Nice ! this suits my needs perfectly 💯 👍 🥇  
Thanks !

**Pull request merged**
